# Generated by Django 6.0.3 on 2026-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rest_breaks', models.IntegerField(blank=True, null=True)),
                ('special_equipment', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
