# Generated by Django 6.0.3 on 2026-03-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.arrangement'),
        ),
    ]
