# Generated by Django 6.0.3 on 2026-03-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='arrangement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.arrangement'),
        ),
    ]
