# Generated by Django 6.0.3 on 2026-03-22 22:52

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_pic_filename),
        ),
    ]
