# Generated by Django 6.0.3 on 2026-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='rest_breaks',
            field=models.BooleanField(default=False),
        ),
    ]
