# Generated by Django 6.0.3 on 2026-03-09 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, null=True)),
                ('question_type', models.IntegerField(blank=True, choices=[(0, 'MCQ'), (1, 'EITHER_OR'), (2, 'SHORT_ANSWER'), (3, 'ESSAY_QUESTION'), (4, 'TEXT_FILLER')], null=True)),
                ('general_feedback', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_sequence', models.IntegerField(default=0)),
                ('option_feedback', models.CharField(blank=True, null=True)),
                ('maximum_mark', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('negative_mark', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='EssayQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_word_length', models.IntegerField(default=0)),
                ('maximum_word_length', models.IntegerField()),
                ('maximum_mark', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('model_answer', models.CharField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='EitherOrOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('order_sequence', models.IntegerField(default=0)),
                ('specific_feedback', models.CharField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_word_length', models.IntegerField()),
                ('use_case', models.BooleanField(default=False)),
                ('answer_text', models.CharField()),
                ('maximum_mark', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='TextFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
