# Generated by Django 6.0.3 on 2026-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eitheroroption',
            name='maximum_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eitheroroption',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='essayquestionoption',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='isMultipleAnswers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortanswerquestionoption',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='textfiller',
            name='maximum_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='textfiller',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
