# Generated by Django 6.0.3 on 2026-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Multiple Choice (MCQ)'), (1, 'Either/Or (True/False)'), (2, 'Short Answer'), (3, 'Essay'), (4, 'Text Filler (Fill in blanks)')]),
        ),
    ]
