# Generated by Django 6.0.3 on 2026-04-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essayquestionoption',
            old_name='maximum_word_length',
            new_name='maximum_word_count',
        ),
        migrations.RenameField(
            model_name='essayquestionoption',
            old_name='minimum_word_length',
            new_name='minimum_word_count',
        ),
    ]
