# Generated by Django 6.0.3 on 2026-04-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_maximum_word_length_essayquestionoption_maximum_word_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortanswerquestionoption',
            old_name='maximum_word_length',
            new_name='maximum_word_count',
        ),
    ]
