# Generated by Django 6.0.3 on 2026-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_maximum_word_length_shortanswerquestionoption_maximum_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortanswerquestionoption',
            name='maximum_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
