# Generated by Django 6.0.3 on 2026-04-10 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_shortanswerquestionoption_maximum_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortanswerquestionoption',
            name='negative_mark',
        ),
        migrations.AddField(
            model_name='shortanswerquestionoption',
            name='is_auto_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortanswerquestionoption',
            name='required_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='shortanswerquestionoption',
            name='use_exact_answer',
            field=models.BooleanField(default=False),
        ),
    ]
