# Generated by Django 6.0.3 on 2026-04-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_shortanswerquestionoption_negative_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortanswerquestionoption',
            name='negative_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
