# Generated by Django 6.0.3 on 2026-04-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_shortanswerquestionoption_negative_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestionoption',
            name='maximum_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
