# Generated by Django 6.0.3 on 2026-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_essayquestionoption_maximum_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestionoption',
            name='marking_rubric',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
