# Generated by Django 6.0.3 on 2026-04-15 16:26

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_essayquestionoption_marking_rubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestionoption',
            name='marking_rubric',
            field=models.FileField(blank=True, null=True, upload_to=questions.models.rubric_file_name),
        ),
    ]
