# Generated by Django 6.0.3 on 2026-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_essayquestionoption_marking_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestionoption',
            name='is_auto_mark',
            field=models.BooleanField(default=False),
        ),
    ]
