# Generated by Django 6.0.3 on 2026-03-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='enrollment',
        ),
    ]
