# Generated by Django 6.0.3 on 2026-03-09 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_students'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_answers', models.BooleanField(default=False)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_attempts', models.IntegerField(blank=True, default=-1, null=True)),
                ('review_attempt', models.BooleanField(blank=True, default=False, null=True)),
                ('review_right_answer', models.BooleanField(blank=True, default=False, null=True)),
                ('review_marks', models.BooleanField(blank=True, default=False, null=True)),
                ('review_specific_feedback', models.BooleanField(blank=True, default=False, null=True)),
                ('review_general_feedback', models.BooleanField(blank=True, default=False, null=True)),
                ('review_overall_feedback', models.BooleanField(blank=True, default=False, null=True)),
                ('show_user_picture', models.BooleanField(blank=True, default=False, null=True)),
                ('delay_between_attempts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anonymise_student', models.BooleanField(blank=True, default=False, null=True)),
                ('anonymise_marker', models.BooleanField(blank=True, default=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'PENDING'), (1, 'IN_MARKING'), (2, 'MARKED')], default=0, null=True)),
                ('total_marks_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sequence', models.IntegerField()),
                ('general_feedback', models.CharField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'PENDING'), (1, 'IN_MARKING'), (2, 'MARKED')], default=0, null=True)),
                ('answer_given', models.CharField(blank=True, null=True)),
                ('marks_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quiz')),
            ],
        ),
    ]
