# Generated by Django 6.0.3 on 2026-04-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_maximum_word_length_shortanswerquestionoption_maximum_word_count'),
        ('quizzes', '0003_attempt_is_completed_attempt_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer_given',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.quizquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('attempt', 'question')},
        ),
        migrations.CreateModel(
            name='ResponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eo_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.eitheroroption')),
                ('mcq_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.mcqoption')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.response')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('eo_option__isnull', False)), fields=('response',), name='unique_eo_per_response')],
            },
        ),
    ]
