# Generated by Django 6.0.3 on 2026-04-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_response_answer_given_alter_response_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.attempt'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizquestion'),
        ),
        migrations.AlterField(
            model_name='responseoption',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='quizzes.response'),
        ),
    ]
