# Generated by Django 6.0.3 on 2026-04-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_response_attempt_alter_response_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='marking_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'MARKED')], default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.IntegerField(choices=[(0, 'CLOSED'), (1, 'OPEN')], default=0),
        ),
    ]
