# Generated by Django 6.0.3 on 2026-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_marking_status_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed / Draft'), (1, 'Manually Open'), (2, 'Scheduled (Automatic)')], default=0),
        ),
    ]
