# Generated by Django 6.0.3 on 2026-04-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_quiz_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='quiz_question',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('attempt', 'quiz_question')},
        ),
    ]
