# Generated by Django 6.0.3 on 2026-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_rename_question_response_quiz_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
