# Generated by Django 6.0.3 on 2026-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_attempt_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='maximum_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
