# Generated by Django 6.0.3 on 2026-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quiz_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='automated_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
