# Generated by Django 6.0.3 on 2026-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_response_automated_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='automated_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
